name: Build Debian Package

on: [workflow_call]

permissions:
  contents: read

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
          source-dir: src
          before-build-hook: debchange --controlmaint -i "Test"
          extra-build-deps: devscripts git